// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Text$BsReactNative = require("bs-react-native/src/components/text.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");

function get(arg, $$default) {
  if (arg) {
    return arg[0];
  } else {
    return $$default;
  }
}

function BoxView(Config) {
  var make = function (p, m, bgColor, $staropt$star) {
    var additionalStyle = $staropt$star ? $staropt$star[0] : Style$BsReactNative.style(/* [] */0);
    var arg = /* Some */[Style$BsReactNative.combine(Curry._3(Config[/* style */0], p, m, bgColor), additionalStyle)];
    return (function (param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8) {
        return (function (param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18) {
            return View$BsReactNative.make(param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, arg, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18);
          });
      });
  };
  return /* module */[/* make */make];
}

function FlexView(Config) {
  var make = function (p, m, direction, content, grow, bgColor, $staropt$star) {
    var additionalStyle = $staropt$star ? $staropt$star[0] : Style$BsReactNative.style(/* [] */0);
    var arg = /* Some */[Style$BsReactNative.combine(Curry._6(Config[/* style */0], p, m, content, direction, grow, bgColor), additionalStyle)];
    return (function (param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8) {
        return (function (param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18) {
            return View$BsReactNative.make(param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, arg, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18);
          });
      });
  };
  return /* module */[/* make */make];
}

function Text(Config) {
  var make = function (p, m, f, color, center, $staropt$star) {
    var additionalStyle = $staropt$star ? $staropt$star[0] : Style$BsReactNative.style(/* [] */0);
    var arg = /* Some */[Style$BsReactNative.combine(Curry._5(Config[/* style */0], p, m, f, color, center), additionalStyle)];
    return (function (param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8) {
        return (function (param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16) {
            return Text$BsReactNative.make(param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, arg, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16);
          });
      });
  };
  return /* module */[/* make */make];
}

exports.get = get;
exports.BoxView = BoxView;
exports.FlexView = FlexView;
exports.Text = Text;
/* Text-BsReactNative Not a pure module */
